"""Recompute exp/out/headroom_by_encoder.json from the committed suite artifacts.

The statistic. For one (encoder, task) pair, the share of the ranking headroom the model's own confidence margin
takes: the gap between a random ranking and a perfect one, and how much of it the margin closes.

    headroom(encoder, task) = 1 - E-AURC(margin) / (AURC(random) - AURC(oracle))

with AURC(random) = e, the unit's error rate, and AURC(oracle) the perfect ranker's. Both facts are derived in
docs/method/protocol.md; the derivations are the reason this file does not simply inline a formula.

Which oracle. The package's `excess_aurc` subtracts `metrics.oracle_aurc(n, k)`, the EXACT finite-n value, so the
numerator of the fraction above is exact. The denominator must use the same oracle or the fraction mixes two
definitions of one quantity. `--oracle asymptotic` reproduces the earlier, inconsistent version for comparison:
it uses e + (1-e) ln(1-e), the n -> infinity limit, which is what docs/claims.yaml divided by until 2026-09-21.
The two differ by O(1/n) and that is not always negligible here, because the suite's smallest tasks carry a few
hundred units. Print the difference with --compare.

    python scripts/headroom_by_encoder.py                  # writes the artifact with the exact oracle
    python scripts/headroom_by_encoder.py --compare        # both oracles side by side, writes nothing

Reads exp/out/exp70_summary.json (OlmoEarth Base) and exp/out/exp74_summary.json (the fifteen other encoders).
Writes exp/out/headroom_by_encoder.json. No network, no cluster, numpy only.
"""
import argparse
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from oe_inferencex import metrics  # noqa: E402

OUT = os.path.join(ROOT, "exp", "out")
SERIES = ("olmoearth_nano", "olmoearth_tiny", "olmoearth_base", "olmoearth_large")


def random_minus_oracle(error_rate, n_units, oracle="exact"):
    """The gap a ranking has to close: a random ranking's AURC minus the perfect one's.

    A random ranking's expected AURC is the error rate itself (protocol.md), so the gap is e - AURC(oracle).
    """
    e = float(error_rate)
    if oracle == "exact":
        n = int(n_units)
        return e - metrics.oracle_aurc(n, int(round(e * n)))
    if oracle == "asymptotic":
        return e - (e + (1.0 - e) * np.log(1.0 - e))
    raise ValueError(f"oracle must be 'exact' or 'asymptotic', got {oracle!r}")


def headroom(rec, oracle="exact"):
    """Share of the gap the margin closes on one task, or None where the gap is undefined."""
    gap = random_minus_oracle(rec["error_rate"], rec["n_units"], oracle)
    if not np.isfinite(gap) or gap <= 0:
        return None
    return 1.0 - rec["signals"]["margin"]["excess_aurc"] / gap


def per_encoder(oracle="exact"):
    """{encoder: [headroom per task]} over the sixteen encoders of the suite."""
    t70 = json.load(open(os.path.join(OUT, "exp70_summary.json")))["results"]["tasks"]
    t74 = json.load(open(os.path.join(OUT, "exp74_summary.json")))["results"]["tasks"]
    out = {}
    for enc, tasks in list(t74.items()) + [("olmoearth_base", t70)]:
        out[enc] = {t: h for t, r in tasks.items() if (h := headroom(r, oracle)) is not None}
    return out


def summarise(per, oracle):
    med = {e: float(np.median(list(v.values()))) for e, v in per.items()}
    by_task = {}
    for e, v in per.items():
        for t, h in v.items():
            by_task.setdefault(t, []).append(h)
    within = float(np.median([np.std(v) for v in by_task.values() if len(v) > 4]))
    between = float(np.std([np.mean(v) for v in by_task.values()]))
    return {
        "oracle": oracle,
        "per_encoder_median_headroom": med,
        "n_encoders": len(med),
        "best": max(med, key=med.get), "best_value": max(med.values()),
        "worst": min(med, key=med.get), "worst_value": min(med.values()),
        "median_across_encoders": float(np.median(list(med.values()))),
        "olmoearth_size_series": {k: med[k] for k in SERIES if k in med},
        "spread_within_task_across_encoders_median_sd": within,
        "spread_between_tasks_sd": between,
        "n_tasks_scored": {e: len(v) for e, v in per.items()},
        "derivation": "1 - excess_aurc(margin) / (e - AURC(oracle)); a random ranking's AURC is the error rate and "
                      "the oracle's is metrics.oracle_aurc(n, k), both derived in docs/method/protocol.md. Median "
                      "over that encoder's tasks. Generated by scripts/headroom_by_encoder.py from the committed "
                      "exp70 and exp74 summaries; no run of its own.",
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--oracle", choices=("exact", "asymptotic"), default="exact")
    ap.add_argument("--compare", action="store_true", help="print both oracles side by side and write nothing")
    args = ap.parse_args()

    if args.compare:
        a, b = summarise(per_encoder("exact"), "exact"), summarise(per_encoder("asymptotic"), "asymptotic")
        ea, eb = a["per_encoder_median_headroom"], b["per_encoder_median_headroom"]
        print(f"{'encoder':26s} {'exact':>9s} {'asymptotic':>11s} {'diff':>10s}")
        for e in sorted(ea, key=lambda k: -ea[k]):
            print(f"{e:26s} {ea[e]:9.4f} {eb[e]:11.4f} {abs(ea[e] - eb[e]):10.2e}")
        print(f"\nmax shift {max(abs(ea[e] - eb[e]) for e in ea):.2e}; "
              f"best {a['best_value']:.3f} vs {b['best_value']:.3f}; worst {a['worst_value']:.3f} vs {b['worst_value']:.3f}")
        return 0

    s = summarise(per_encoder(args.oracle), args.oracle)
    path = os.path.join(OUT, "headroom_by_encoder.json")
    with open(path, "w") as f:
        json.dump(s, f, indent=1)
    print(f"wrote {path} with the {args.oracle} oracle")
    print(f"  {s['n_encoders']} encoders | best {s['best']} {s['best_value']:.4f} | worst {s['worst']} {s['worst_value']:.4f}")
    print(f"  median across encoders {s['median_across_encoders']:.4f} | "
          f"between-task sd {s['spread_between_tasks_sd']:.3f} vs within-task sd {s['spread_within_task_across_encoders_median_sd']:.3f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
